spring:
  profiles.include: okta-dev7, server-debug
simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  patient-link-url: https://dev7.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://dev7.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simplereportdev7app.z13.web.core.windows.net
      - https://simple-report-api-dev7.azurewebsites.net
      - https://simple-report-dev7.azureedge.net
      - https://dev7.simplereport.gov
twilio:
  enabled: true
