spring:
  profiles.include: okta-dev5, server-debug
simple-report:
  azure-reporting-queue:
    enabled: true
    fhir-queue-enabled: true
    exception-webhook-enabled: true
  patient-link-url: https://dev5.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://dev5.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simplereportdev5app.z13.web.core.windows.net
      - https://simple-report-api-dev5.azurewebsites.net
      - https://simple-report-dev5.azureedge.net
      - https://dev5.simplereport.gov
twilio:
  enabled: true
