spring:
  profiles.include: no-security, no-okta-mgmt, create-sample-data, no-okta-auth, no-experian
simple-report:
  patient-link-url: https://demo.simplereport.gov/app/pxp?plid=
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simple-report-api-demo.azurewebsites.net
      - https://simple-report-demo.azureedge.net
      - https://demo.simplereport.gov
twilio:
  enabled: false
