simple-report:
  patient-link-url: https://training.simplereport.gov/app/pxp?plid=
  twilio-callback-url: https://training.simplereport.gov/api/pxp/callback
  sendgrid:
    enabled: false
  cors:
    allowed-origins:
      - https://simple-report-api-training.azurewebsites.net
      - https://simple-report-training.azureedge.net
      - https://training.simplereport.gov
twilio:
  enabled: false
features:
  testCardRefactorEnabled: true