spring:
  profiles.include: okta-prod
simple-report:
  data-hub:
    upload-enabled: true
    upload-url: "https://prime-data-hub-prod.azurefd.net/api/reports"
  cors:
    allowed-origins:
      - https://www.simplereport.gov
      - https://simplereport.gov
