name: Deploy Back-end API

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - tim-best/add-date-field
    paths:
      - "backend/**"
  schedule:
    - cron: "04 12 * * *" # deploy main every day at 12:04 UTC

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Java Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-build-${{ hashFiles('*.gradle', 'gradle/dependency-locks/*') }}
      - name: Build Boot Jar
        run: ./gradlew bootJar
      - name: Deploy to cloud.gov
        uses: usds/cloud-gov-cli@master
        with:
          org: ${{secrets.CLOUD_GOV_ORG}}
          user: ${{secrets.SERVICE_USER}}
          password: ${{secrets.SERVICE_PASSWORD}}
          manifest: backend/manifest.yml
