name: Test Liquibase Actions

# Run this on pushes to any branch that changes a Liquibase changelog
on:
  workflow_call:
    inputs:
      DOCKER_DATABASE_IMAGE_VERSION:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test-db-liquibase-action
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend

jobs:
  test-db-liquibase-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Start DB
        env:
          DOCKER_DATABASE_IMAGE_VERSION: ${{ inputs.DOCKER_DATABASE_IMAGE_VERSION }}
        run: touch ../.env && docker compose -f ../docker-compose.yml up -d db
      - name: Build rollback image
        run: docker compose -f docker-compose.db-liquibase-action.yml build
      - name: Run forward migrations
        run: docker compose -f docker-compose.db-liquibase-action.yml run --entrypoint "gradle liquibaseUpdate" db_liquibase_action
      - name: Run liquibase validation
        run: docker compose -f docker-compose.db-liquibase-action.yml run --env "LIQUIBASE_ACTION=validate" db_liquibase_action
      - name: Run liquibase clear checksums
        run: docker compose -f docker-compose.db-liquibase-action.yml run --env "LIQUIBASE_ACTION=clear-checksums" db_liquibase_action
      - name: Test rolling back on last 20 migrations
        run: docker compose -f docker-compose.db-liquibase-action.yml run --entrypoint "gradle liquibaseRollbackCount -PliquibaseCount=20" db_liquibase_action